#!/usr/bin/env bash
#Displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line

e=0

while [ $e -lt 10 ]
do
	if [ $e -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( e++ ))
done
