#!/usr/bin/env bash
#Displays bad luck on 4th loop iteration
#Displays good luck on 8th loop iteration
#Displays Best School for other iterations
loop=1
while
	[ $loop lt -10]
do
	if [ $loop eq -4 ]
	then
		echo "bad luck"
	elif [ $loop eq -8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( loop ++ ))
done
