#!/usr/bin/env bash
#Bash script that displays number from 1 to 20
#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration

switch=1

while [ $switch -le 20 ]
do
	echo "$switch"
	case $switch in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( switch ++ ))
done
