#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes
#Displays hours from 0 to 12
#Displays minutes from 1 to 59

time=0

while [ $time -le 12 ]
do
	echo "Hour: $time"
	minute=1
	while [ $minute -le 59 ]
	do
		echo "$minute"
		(( minute ++ ))
	done
	(( time ++ ))
done
