#!/usr/bin/env bash
#Script that indefinitely writes "I am alive" to the file /tmp/my_process.
#And pauses two seconds in between each message
while true
do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done
